### ISSUE TITLE
Prototipo - RA

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-equipo-de-la-chica-tec#1]
[Prototipo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-equipo-de-la-chica-tec/files/10846332/Prototipo.pdf)

**Comment by josealfredo79** [comment]
calificacion...

**Comment by uzias10** [comment]
Buen trabajo: 18/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
